src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SortieRepository::class)]
class Sortie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\Length(max: 255, maxMessage: 'Le champ nom de sortie n\'accepte que 255 caractères maximum.')]
    #[Assert\Type('string')]
    #[Assert\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[Assert\NotBlank]
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\GreaterThanOrEqual('today')]
    private ?\DateTimeInterface $dateHeureDebut = null;

    #[Assert\NotBlank]
    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $duree = null;

    #[Assert\NotBlank]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\GreaterThanOrEqual('today')]
    private ?\DateTimeInterface $dateLimitInscription = null;

    #[Assert\PositiveOrZero]
    #[Assert\Type('integer')]
    #[Assert\NotBlank]
    #[ORM\Column(nullable: true)]
    private ?int $nbInscriptionsMax = null;

    #[Assert\Length(max: 255, maxMessage: 'Le champ infos sortie n\'accepte que 255 caractères maximum.')]
    #[Assert\Type('string')]
    #[Assert\NotBlank]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $InfosSortie = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Etat $etat = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Lieu $lieu = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Site $site = null;

    #[ORM\ManyToOne(inversedBy: 'sortiesO')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $organisateur = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'sortiesP')]
    private Collection $participant;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $motifAnnulation = null;


    public function __construct()
    {
        $this->participant = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateHeureDebut(): ?\DateTimeInterface
    {
        return $this->dateHeureDebut;
    }

    public function setDateHeureDebut(\DateTimeInterface $dateHeureDebut): self
    {
        $this->dateHeureDebut = $dateHeureDebut;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(?\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateLimitInscription(): ?\DateTimeInterface
    {
        return $this->dateLimitInscription;
    }

    public function setDateLimitInscription(?\DateTimeInterface $dateLimitInscription): self
    {
        $this->dateLimitInscription = $dateLimitInscription;

        return $this;
    }

    public function getNbInscriptionsMax(): ?int
    {
        return $this->nbInscriptionsMax;
    }

    public function setNbInscriptionsMax(?int $nbInscriptionsMax): self
    {
        $this->nbInscriptionsMax = $nbInscriptionsMax;

        return $this;
    }

    public function getInfosSortie(): ?string
    {
        return $this->InfosSortie;
    }

    public function setInfosSortie(?string $InfosSortie): self
    {
        $this->InfosSortie = $InfosSortie;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): self
    {
        $this->site = $site;

        return $this;
    }

    public function getOrganisateur(): ?User
    {
        return $this->organisateur;
    }

    public function setOrganisateur(?User $organisateur): self
    {
        $this->organisateur = $organisateur;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getParticipant(): Collection
    {
        return $this->participant;
    }

    public function addParticipant(User $participant): self
    {
        if (!$this->participant->contains($participant)) {
            $this->participant->add($participant);
        }

        return $this;
    }

    public function removeParticipant(User $participant): self
    {
        $this->participant->removeElement($participant);

        return $this;
    }

    public function getMotifAnnulation(): ?string
    {
        return $this->motifAnnulation;
    }

    public function setMotifAnnulation(?string $motifAnnulation): self
    {
        $this->motifAnnulation = $motifAnnulation;

        return $this;
    }


}

src/Controller/SortieController.php
<?php

namespace App\Controller;


use App\Entity\Groupe;
use App\Entity\Lieu;
use App\Entity\Sortie;
use App\Entity\User;
use App\Form\AnnulerSortieType;
use App\Form\GroupeType;
use App\Form\LieuType;
use App\Form\ModifierSortieType;
use App\Form\SortieType;
use App\Form\UserType;
use App\Repository\EtatRepository;
use App\Repository\GroupeRepository;
use App\Repository\LieuRepository;
use App\Repository\SiteRepository;
use App\Repository\SortieRepository;
use App\Repository\UserRepository;
use App\Repository\VilleRepository;
use DateInterval;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use function Sodium\add;

#[IsGranted('ROLE_USER')]
#[Route('/', name: 'sortie')]
class SortieController extends AbstractController
{
    /**
     * Lister les sorties pour la page d'accueil
     * @param SortieRepository $sortieRepository
     * @param SiteRepository $siteRepository
     * @param UserRepository $userRepository
     * @param EtatRepository $etatRepository
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return Response
     */
    #[Route('', name: '_list')]
    public function list(
        SortieRepository       $sortieRepository,
        SiteRepository         $siteRepository,
        UserRepository         $userRepository,
        EtatRepository         $etatRepository,
        EntityManagerInterface $em,
        Request                $request
    ): Response
    {
        $idUser = $userRepository->findOneBy(['email' => $this->getUser()->getUserIdentifier()]);
        if (!$idUser->isActif()) {
            return $this->redirectToRoute('app_logout');
        }

        // récupération des éléments de traitement
        $date = new \DateTime();
        $sites = $siteRepository->findAll();
        $etatCloturee = $etatRepository->findOneBy(['libelle' => 'Clôturée']);
        $etatCree = $etatRepository->findOneBy(['libelle' => 'Créée']);


        // traitement si filtres activés
        if (
            $request->query->get('site') != null ||
            $request->query->get('motsclefs') != null ||
            $request->query->get('datedebut') != null ||
            $request->query->get('datefin') != null ||
            $request->query->get('organisateur') != false ||
            $request->query->get('incrit') != false ||
            $request->query->get('noninscrit') != false ||
            $request->query->get('passees') != false
        ) {

            $site = $request->query->get('site');
            $motsclefs = $request->query->get('motsclefs');
            $datedebut = $request->query->get('datedebut');
            $datefin = $request->query->get('datefin');
            $organisateur = ($request->query->get('organisateur') == 'on') ? true : false;
            $inscrit = ($request->query->get('incrit') == 'on') ? true : false;
            $noninscrit = ($request->query->get('noninscrit') == 'on') ? true : false;
            $passees = ($request->query->get('passees') == 'on') ? true : false;
            $criteres = [
                'site' => $site,
                'motsclefs' => $motsclefs,
                'datedebut' => $datedebut,
                'datefin' => $datefin,
                'organisateur' => $organisateur,
                'inscrit' => $inscrit,
                'noninscrit' => $noninscrit,
                'passees' => $passees
            ];

            $sorties = $sortieRepository->filtreSorties(
                $site,
                $motsclefs,
                $datedebut,
                $datefin,
                $userRepository->findOneBy([
                    'id' => $this->getUser()]),
                $organisateur,
                $inscrit,
                $noninscrit,
                $passees);

        } else {
            // traitement si aucun filtre = findall
            $sorties = $sortieRepository->findAll();
            $criteres = [
                'site' => null,
                'motsclefs' => null,
                'datedebut' => null,
                'datefin' => null,
                'organisateur' => null,
                'inscrit' => null,
                'noninscrit' => null,
                'passees' => null
            ];
        }

        foreach ($sorties as $sortie) {
            // sorties datedébut m-1 et plus
            if ($sortie->getDateHeureDebut() < date_sub($date, new DateInterval('P1M'))) {
                unset($sorties[array_search($sortie, $sorties, true)]);
            }

            // sorties != état créé & user non organisateur
            if ($sortie->getOrganisateur() != $idUser) {
                if ($sortie->getEtat() == $etatCree) {
                    unset($sorties[array_search($sortie, $sorties, true)]);
                }
            }

            // clôture sorties date inscription dépassée
            if ($date >= $sortie->getDateLimitInscription()) {
                $sortie->setEtat($etatCloturee);
                $em->persist($sortie);
                $em->flush();
            }
        }

        return $this->render('sortie/list.html.twig',
            [
                'sorties' => $sorties,
                'sites' => $sites,
                'date' => $date,
                'criteres' => $criteres
            ]);
    }

    /**
     * Afficher une sortie
     * @param SortieRepository $sortieRepository
     * @param int $id
     * @return Response
     */
    #[Route('/sortie/{id}', name: '_afficher')]
    public function afficher(
        SortieRepository $sortieRepository,
        int              $id,
    ): Response
    {
        $date = new \DateTime();
        $sortie = $sortieRepository->findOneBy(['id' => $id]);
        if ($sortie->getDateHeureDebut() < date_sub($date, new DateInterval('P1M'))) {
            $this->addFlash('Sortie non consultable', 'La sortie sélectionnée est trop ancienne pour être consultée.');
            return $this->redirectToRoute('sortie_list');
        } else {
            return $this->render('sortie/afficher.html.twig',
                [
                    'sortie' => $sortie
                ]);
        }
    }

    /**
     * Publier une sortie
     * @param SortieRepository $sortieRepository
     * @param EtatRepository $etatRepository
     * @param EntityManagerInterface $em
     * @param int $id
     * @return Response
     */
    #[Route('/sortie/publier/{id}', name: '_publier')]
    public function publier(
        SortieRepository       $sortieRepository,
        EtatRepository         $etatRepository,
        EntityManagerInterface $em,
        int                    $id
    ): Response
    {
        $sortie = $sortieRepository->findOneBy(['id' => $id]);
        $sortie->setEtat($etatRepository->findOneBy(['libelle' => 'Ouverte']));
        try {
            $em->persist($sortie);
            $em->flush();
            $this->addFlash('Sortie publiée', 'Sortie publiée avec succès.');
        } catch (Exception $exception) {
            $this->addFlash('Sortie non publiée', 'Détail de l\'erreur : ' . $exception->getMessage() . '.');
        }
        return $this->redirectToRoute('sortie_list');
    }

    /**
     * Annuler une sortie
     * @param SortieRepository $sortieRepository
     * @param int $id
     * @param Request $request
     * @param EtatRepository $etatRepository
     * @param EntityManagerInterface $em
     * @return Response
     */
    #[Route('/sortie/annuler/{id}', name: '_annuler')]
    public function annuler(
        SortieRepository       $sortieRepository,
        int                    $id,
        Request                $request,
        EtatRepository         $etatRepository,
        EntityManagerInterface $em
    ): Response
    {
        $sortie = new Sortie();
        $sortie = $sortieRepository->findOneBy(['id' => $id]);
        $sortieForm = $this->createForm(AnnulerSortieType::class, $sortie);
        $sortieForm->handleRequest($request);

        if ($sortieForm->isSubmitted()) {
            try {
                // Je récupère en base de donnée l'état créé
                $etatAnn = $etatRepository->findOneBy(['libelle' => 'Annulée']);
                if ($etatAnn) {
                    $sortie->setEtat($etatAnn);
                    if ($sortieForm->isValid()) {
                        $em->persist($sortie);
                    }
                }
            } catch (Exception $exception) {
                dd($exception->getMessage());
            }
            $em->flush();
            $this->addFlash('Sortie annulée', 'Sortie annulée avec succès.');
            return $this->redirectToRoute('sortie_list');
        }
        return $this->render('sortie/annuler.html.twig',
            compact('sortieForm', 'sortie')
        );
    }

    /**
     * Créer une sortie
     * @param EntityManagerInterface $em
     * @param Request $request
     * @param EtatRepository $etatRepository
     * @param SortieRepository $sortieRepository
     * @param LieuRepository $lieuRepository
     * @param VilleRepository $villeRepository
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    #[Route('/create', name: '_create')]
    public function create(
        EntityManagerInterface $em,
        Request                $request,
        EtatRepository         $etatRepository,
        SortieRepository       $sortieRepository,
        LieuRepository         $lieuRepository,
        VilleRepository        $villeRepository
    )
    {

        $sortie = new Sortie();
        $sortieForm = $this->createForm(SortieType::class, $sortie);
        $sortieForm->handleRequest($request);
        $sortie->setOrganisateur($this->getUser());
        $lieux = $lieuRepository->findAll();
        $villes = $villeRepository->findAll();

templates/sortie/afficher.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h2 class="text-center">Afficher une sortie</h2>
<div>
    <p class="text-center">
        <span class="bold">{{ sortie.nom }}</span><br>
        Date de la sortie : {{ sortie.dateHeureDebut | date('d/m/Y H:i') }}<br><br>
        Limite des inscriptions : {{ sortie.dateLimitInscription | date('d/m/Y') }}<br>
        Inscrits : {{ sortie.participant|length }} / {{ sortie.nbInscriptionsMax }}<br>
        Durée : {{ sortie.duree | date('H:i') }}<br>
        Site : {{ sortie.site.nom }}<br><br>
        Lieu : {{ sortie.lieu.nom }}<br>
        Rue : {{ sortie.lieu.rue }}<br>
        Code postal : {{ sortie.lieu.ville.codePostal }}<br><br>
        Infos : {{ sortie.infosSortie }}<br>
    </p>

    <input type="hidden" id="latitude" value="{{ sortie.lieu.latitude }}">
    <input type="hidden" id="longitude" value="{{ sortie.lieu.longitude }}">


        <h2 class="text-center">Liste des participants</h2>
        <div class="tab center text-center">
            <div class="tab-titre center text-center">
                <div>Pseudo</div>
                <div>Nom</div>
            </div>
        </div>


            {% for leparticipant in sortie.participant %}
                <div class="tab-data center text-center ">
                    <div>{{ leparticipant.pseudo }}</div>
                    <div>{{ leparticipant.prenom }} {{ leparticipant.nom }}</div>
                    <a href="{{ path('profil_afficher', {id : leparticipant.id}) }}">
                        <button>Son profil</button>
                    </a>
                </div>
            {% endfor %}

    </div>
    <br>

    {% if app.user in sortie.participant %}
        <div class="flex-row center">
            <h2> Groupe privé</h2>
            <a href="{{ path('sortie_groupe', {id : sortie.id}) }}" class="btn">Créer un groupe privé</a>
            <a class="btn" href="{{ path('sortie_ajouterParticipant', {id : sortie.id }) }}">Ajouter des membres</a>
        </div>
    {% endif %}

    <div id="map"></div>

    <script type="text/javascript">
        var options = { // LIGNE 16
            center: new google.maps.LatLng(
                document.getElementById('latitude').value,
                document.getElementById('longitude').value),
            zoom: 15
        };

        var map = new google.maps.Map(document.getElementById("map"), options);

        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(document.getElementById('latitude').value,
                document.getElementById('longitude').value),
            map: map,
            title: 'Rendez-vous ici !'
        })
    </script>

    {% endblock %}

    {% block title %}
        {{ parent() }}Sortie : {{ sortie.nom }}
    {% endblock %}

templates/sortie/ajouterParticipant.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Groupe privée </h2>

    <div class="flex-row center">
        <h1>Groupe privée {{ groupe.nom }}</h1>

        <h2>Ajouter des membres au groupe</h2>
    <h2>Liste des participants à la sortie</h2>
    <div class="tab">
        <div class="tab-titre">
            <div>Pseudo</div>
            <div>Nom</div>
            <label>Membre</label>
            <div>Action</div>
        </div>

        {% for leparticipant in sortie.participant %}
            <div class="tab-data">
                <div>{{ leparticipant.pseudo }}</div>
                <div>{{ leparticipant.prenom }} {{ leparticipant.nom }}</div>
                <label class="inscrit">{{ (leparticipant in groupe.participant) ? 'X' : '' }}</label>
                {% if leparticipant in groupe.participant %}
                    <a href="{{ path('sortie_exclure', {id : groupe.id, idUser : leparticipant.id, idSortie : sortie.id}) }}">Exclure</a>
                {% else %}
                    <a href="{{ path('sortie_ajouter', {id : groupe.id, idUser : leparticipant.id, idSortie : sortie.id}) }}">Ajouter</a>
                {% endif %}

                </div>
            {% endfor %}
        </div>

        <a class="btn" href="{{ path('sortie_afficher', {id : sortie.id}) }}">Revenir à la sortie</a>
    </div>

{% endblock %}

{% block title %}
    {{ parent() }}Groupe : {{ groupe.nom }}
{% endblock %}

templates/sortie/annuler.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }}Annuler la sortie {{ sortie.nom }}
{% endblock %}

{% block body %}
    <h2>Annuler une sortie</h2>
    <ul>
        <li>Nom de la sortie : {{ sortie.nom }}</li>
        <li>Date de la sortie : {{ sortie.dateHeureDebut | date('d/m/Y') }}</li>
        <li>Ville organisatrice : {{ sortie.site.nom }}</li>
        <li>Lieu
            : {{ sortie.lieu.nom }} {{ sortie.lieu.rue }} {{ sortie.lieu.ville.codePostal }} {{ sortie.lieu.ville.nom }}
        <li>{{ form(sortieForm) }} <a href="{{ path('sortie_list') }}">
                <button>Annuler</button>
            </a></li>
    </ul>

{% endblock %}

templates/sortie/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }}Créer une sortie
{% endblock %}

{% block body %}

    <h2 class="text-center">Créer une sortie</h2>

    <div class="text-center neon-no-hover">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="alter-{{ label }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>

    <div class="flex-row center ">

        {{ form_start(sortieForm) }}

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(sortieForm.lieu) }} :</label>
            <div>{{ form_widget(sortieForm.lieu) }}
                {% if not app.flashes %}
                    <a href="{{ path('sortie_ajouterlieu') }}" class="btn-plus margin-xs">
                        +
                    </a>
                {% endif %}
            </div>
            <br><br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(sortieForm.nom) }} :</label>
            <div>{{ form_widget(sortieForm.nom) }}</div>
            <br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(sortieForm.dateHeureDebut) }} :</label>
            <div>{{ form_widget(sortieForm.dateHeureDebut) }}</div>
            <br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(sortieForm.dateLimitInscription) }} :</label>
            <div>{{ form_widget(sortieForm.dateLimitInscription) }}</div>
            <br>
        </div>
        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(sortieForm.nbInscriptionsMax) }} :</label>
            <div>{{ form_widget(sortieForm.nbInscriptionsMax) }}</div>
            <br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(sortieForm.duree) }} :</label>
            <div>{{ form_widget(sortieForm.duree) }}</div>
            <br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(sortieForm.InfosSortie) }} :</label>
            <div>{{ form_widget(sortieForm.InfosSortie) }}</div>
            <br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(sortieForm.site) }} :</label>
            <div>{{ form_widget(sortieForm.site) }}</div>
            <br>
        </div>
        <br><br>


        <div class="flex-col center">
            <div>{{ form_widget(sortieForm.Enregistrer) }}</div>
            <div>{{ form_widget(sortieForm.Publier) }}</div>
            <a class="btn" href="{{ path('sortie_list') }}">Annuler</a>
        </div>
        {{ form_end(sortieForm) }}

    </div>

{% endblock %}

templates/sortie/groupe.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }}Créer un groupe
{% endblock %}

{% block body %}
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="alter-{{ label }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    {% if not groupeExist %}
        <div class="flex-row center">
            <h2>Créer un groupe privé</h1>

            <div>
                {{ form_start(groupeForm) }}
                <p>Nom du groupe : {{ form_widget(groupeForm.nom) }}</p>
            </div>
            <div class="flex-row">
                <input type="submit" class="btn" href="{{ path('sortie_ajouterParticipant', {id : sortie.id}) }}" value="Créer">
                {{ form_end(groupeForm) }}
                <a class="btn" href="{{ path('sortie_afficher', {id : sortie.id}) }}" >Annuler</a>
            </div>
        </div>
    {% else %}
        <div class="flex-row center">
            <h2>Un groupe existe déjà pour cette sortie </h1>
            <a class="btn" href="{{ path('sortie_ajouterParticipant', {id : sortie.id }) }}">Ajouter des membres</a>
            <a class="btn" href="{{ path('sortie_afficher', {id : sortie.id}) }}">Revenir à la sortie</a>
        </div>

    {% endif %}

{% endblock %}

templates/sortie/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }}Modifier une sortie
{% endblock %}

{% block body %}
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="alter-{{ label }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}
    <h2 class="text-center">Modifier une sortie</h1>

    <div class="flex-row center ">
        {{ form_start(modifierSortieForm) }}
        <div class="flex-col">
            <label class="bold margin-right-xs label" >{{ field_label(modifierSortieForm.nom) }} :</label>
            <div>{{ form_widget(modifierSortieForm.nom) }}</div><br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(modifierSortieForm.dateHeureDebut) }} :</label>
            <div>{{ form_widget(modifierSortieForm.dateHeureDebut) }}</div><br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(modifierSortieForm.dateLimitInscription) }} :</label>
            <div>{{ form_widget(modifierSortieForm.dateLimitInscription) }}</div><br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(modifierSortieForm.nbInscriptionsMax) }} :</label>
            <div>{{ form_widget(modifierSortieForm.nbInscriptionsMax) }}</div><br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(modifierSortieForm.duree) }} :</label>
            <div>{{ form_widget(modifierSortieForm.duree) }}</div><br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(modifierSortieForm.InfosSortie) }} :</label>
            <div>{{ form_widget(modifierSortieForm.InfosSortie) }}</div><br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(modifierSortieForm.site) }} :</label>
            <div>{{ form_widget(modifierSortieForm.site) }}</div><br>
        </div>

        <div class="flex-col">
            <label class="bold margin-right-xs label">{{ field_label(modifierSortieForm.lieu) }} :</label>
            <div>{{ form_widget(modifierSortieForm.lieu) }}</div><br><br><br>
        </div>

        <div class="flex-col center" >
            <div>{{ form_widget(modifierSortieForm.Enregistrer) }}</div>
            <div>{{ form_widget(modifierSortieForm.Publier) }}</div>
            <a class="btn" href="{{ path('sortie_list') }}">Annuler</a>

        </div>

        {{ form_end(modifierSortieForm) }}

    </div>
{% endblock %}